{% set name = "importhook" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06db03a92010036bd5f09c6cab8f37b6656e90a6cc591061ddbd3d4e775b4400

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - python >=3

test:
  imports:
    - importhook

about:
  home: https://github.com/brettlangdon/importhook
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Execute code when certain modules are imported
  doc_url: https://brettlangdon.github.io/importhook/

extra:
  recipe-maintainers:
    - tschoonj
