{% set name = "importhook" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 635ad367225fa022221025545c167b09d09ada671821b6e587df0d5ae4bf0aab

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - importhook

about:
  home: https://github.com/brettlangdon/importhook
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Execute code when certain modules are imported
  doc_url: https://brettlangdon.github.io/importhook/

extra:
  recipe-maintainers:
    - tschoonj
